# Generated by Django 5.0.2 on 2024-10-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0028_alter_paso_image_alter_tour_imagen'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='original',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='paso',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Tour_audio/'),
        ),
        migrations.AlterField(
            model_name='paso',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='Tour_imagen/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='Tour_audio/'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='imagen',
            field=models.ImageField(max_length=255, upload_to='Tour_imagen/'),
        ),
    ]
