# Generated by Django 5.0.2 on 2025-01-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LTtApp', '0029_tour_original_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepAlive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tour',
            name='suma_valoraciones',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tour',
            name='total_valoraciones',
            field=models.IntegerField(default=0),
        ),
    ]
